plugins:
  # - remark-preset-lint-markdown-style-guide 
  - remark-preset-lint-recommended
  - remark-preset-lint-consistent
  - remark-lint-match-punctuation
  # - remark-lint-heading-whitespace
  # - remark-lint-no-dead-urls
  # - remark-lint-code
